version: '2'
services:
    db:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
        ports:
            - 5431:5432
        # volumes:
        #    - ./db:/var/lib/postgresql

    redis:
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - ./redis:/data

    django-admin:
        build: ./db/
        command: python manage.py runserver 0.0.0.0:8000
        ports:
        - "8000:8000"
        depends_on:
        - db