# Generated by Django 2.0.6 on 2018-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='persons',
            field=models.ManyToManyField(blank=True, null=True, to='groups.PersonsType'),
        ),
        migrations.AlterField(
            model_name='personstype',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='groups.Group'),
        ),
    ]
